Repository sifive/wit, pull requests merged in 2019-07, with the labels that each got.

#88 fix confusing error messages when updating package
  lib/wit/workspace.py
Labels: squash and merge please

#112 Fix --version for installs
  lib/wit/main.py
  t/install.t
Labels: merge commit please

#125 show results while regress.sh is running
  t/regress.sh
Labels: enhancement
